name: Impact
version: 2.0.0
description: Causes falling players to crater on impact.
author: SableDnah
website: http://dev.bukkit.org/server-mods/impact/

main: me.sablednah.impact.Impact
softdepend: [ Spout, CreeperHeal, Factions ]

commands:
    impact:
        description: Root command for all  Impact Commands.
        usage: /<command> [reload]

permissions:
    impact.nocrater:
        description: Players with this node do not leave craters.
        default: false
    impact.reload:
        description: Players with this node can reload config.
        default: op
